/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.dao.graphique;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 * It serves for choosing RSS feed filters.
 */
public class ChooseEventTypeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EventsFrame
     */
    public ChooseEventTypeFrame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filmCheckBox = new javax.swing.JCheckBox();
        conferenceCheckBox = new javax.swing.JCheckBox();
        workshopCheckBox = new javax.swing.JCheckBox();
        otherCheckBox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Type des experiances");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(26, 24, 190, 19);

        filmCheckBox.setText("voyage");
        jPanel1.add(filmCheckBox);
        filmCheckBox.setBounds(10, 70, 90, 23);

        conferenceCheckBox.setText("sejour");
        jPanel1.add(conferenceCheckBox);
        conferenceCheckBox.setBounds(10, 110, 100, 23);

        workshopCheckBox.setText("croisiere");
        jPanel1.add(workshopCheckBox);
        workshopCheckBox.setBounds(10, 150, 100, 23);

        otherCheckBox.setText("hotel");
        jPanel1.add(otherCheckBox);
        otherCheckBox.setBounds(10, 190, 80, 23);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);
        okButton.setBounds(10, 250, 47, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(41, 56, 313, 2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/agence-de-voyage1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 40, 280, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        RSSFeedReader reader=new RSSFeedReader();
        String params="fluxrss";
        List<String> values=new ArrayList<String>();
        
        if(filmCheckBox.isSelected()){
            values.add("hotel.xml");
        }
        if(conferenceCheckBox.isSelected()){
            values.add("voyage.xml");     
        }
        if(workshopCheckBox.isSelected()){
            values.add("sejour.xml");
        }
        if(otherCheckBox.isSelected()){
            values.add("croisiere.xml");
        }
        
        if(values.size()>0){
            for(int i=0;i<values.size();i++){
                params+=values.get(i);
                if(i!=values.size()-1){
                    params+=",";
                }
            }
            
            reader.setBaseUrl(reader.getBaseUrl()+params);
        }
        
        this.setVisible(false);
        EventsFrame f=new EventsFrame(reader.getBaseUrl());
        f.setVisible(true);
     
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseEventTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseEventTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseEventTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseEventTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseEventTypeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox conferenceCheckBox;
    private javax.swing.JCheckBox filmCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox otherCheckBox;
    private javax.swing.JCheckBox workshopCheckBox;
    // End of variables declaration//GEN-END:variables
}
