/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.dao.graphique;

import com.esprit.dao.entities.*;
import com.esprit.implementations.*;
import com.esprit.implementations.HotelDAO;
import java.awt.BorderLayout;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mehdikarray
 */
public class frameadmin extends javax.swing.JFrame {

    /**
     * Creates new form frameadmin
     */
    public frameadmin() {
         
//        stat.setLayout(new BorderLayout());
//        stat.add(new NbrRDVAgentAgence(),BorderLayout.PAGE_START);
//        stat.validate();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        font = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        listehotel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable3 = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        suphot = new javax.swing.JButton();
        listdestination = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledestination = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        supdes = new javax.swing.JButton();
        listtransport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modftra = new javax.swing.JButton();
        suptran = new javax.swing.JButton();
        listerestaurant = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        restmodf = new javax.swing.JButton();
        ressup = new javax.swing.JButton();
        listelocationvacance = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        vacmodif = new javax.swing.JButton();
        vacsup = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Administrateur");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        font.setBackground(new java.awt.Color(255, 255, 255));

        Data.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("DATA");

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Afficher");

        jCheckBox2.setText("Ajouter");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hotels", "Restaurent", "Destination", "Location de vacance", "Transport" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        listehotel.setBackground(new java.awt.Color(255, 255, 255));
        listehotel.setPreferredSize(new java.awt.Dimension(300, 277));

        JTable3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102))));
        JTable3.setModel(new AfficherHotel());
        jScrollPane3.setViewportView(JTable3);

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        suphot.setText("Supprimer");
        suphot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suphotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listehotelLayout = new javax.swing.GroupLayout(listehotel);
        listehotel.setLayout(listehotelLayout);
        listehotelLayout.setHorizontalGroup(
            listehotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listehotelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(suphot)
                .addGap(41, 41, 41))
            .addGroup(listehotelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        listehotelLayout.setVerticalGroup(
            listehotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listehotelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listehotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suphot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        listdestination.setBackground(new java.awt.Color(255, 255, 255));

        tabledestination.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102))));
        tabledestination.setModel(new AfficherDestinationFrameadmin());
        jScrollPane2.setViewportView(tabledestination);

        jButton8.setText("modifier");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        supdes.setText("Supprimer");
        supdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listdestinationLayout = new javax.swing.GroupLayout(listdestination);
        listdestination.setLayout(listdestinationLayout);
        listdestinationLayout.setHorizontalGroup(
            listdestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listdestinationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listdestinationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(supdes)
                .addGap(47, 47, 47))
        );
        listdestinationLayout.setVerticalGroup(
            listdestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listdestinationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listdestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supdes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listtransport.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new AfficherTransportFrameadmin());
        jScrollPane1.setViewportView(jTable1);

        modftra.setText("Modifier");
        modftra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modftraActionPerformed(evt);
            }
        });

        suptran.setText("Supprimer");
        suptran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suptranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listtransportLayout = new javax.swing.GroupLayout(listtransport);
        listtransport.setLayout(listtransportLayout);
        listtransportLayout.setHorizontalGroup(
            listtransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listtransportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modftra, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(suptran)
                .addGap(37, 37, 37))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        listtransportLayout.setVerticalGroup(
            listtransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listtransportLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(listtransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modftra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suptran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        listerestaurant.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102))));
        jTable5.setModel(new AfficheRestaurant());
        jScrollPane4.setViewportView(jTable5);

        restmodf.setText("Modifier");
        restmodf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restmodfActionPerformed(evt);
            }
        });

        ressup.setText("Supprimer");
        ressup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ressupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listerestaurantLayout = new javax.swing.GroupLayout(listerestaurant);
        listerestaurant.setLayout(listerestaurantLayout);
        listerestaurantLayout.setHorizontalGroup(
            listerestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listerestaurantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listerestaurantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(restmodf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ressup)
                .addGap(42, 42, 42))
        );
        listerestaurantLayout.setVerticalGroup(
            listerestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listerestaurantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(listerestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restmodf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        listelocationvacance.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102))));
        jTable4.setModel(new Affichelocation());
        jScrollPane5.setViewportView(jTable4);

        vacmodif.setText("Modifier");
        vacmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacmodifActionPerformed(evt);
            }
        });

        vacsup.setText("Supprimer");
        vacsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacsupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listelocationvacanceLayout = new javax.swing.GroupLayout(listelocationvacance);
        listelocationvacance.setLayout(listelocationvacanceLayout);
        listelocationvacanceLayout.setHorizontalGroup(
            listelocationvacanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listelocationvacanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listelocationvacanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vacmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(vacsup)
                .addGap(42, 42, 42))
        );
        listelocationvacanceLayout.setVerticalGroup(
            listelocationvacanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listelocationvacanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listelocationvacanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacsup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DataLayout = new javax.swing.GroupLayout(Data);
        Data.setLayout(DataLayout);
        DataLayout.setHorizontalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jCheckBox1)
                        .addGap(38, 38, 38)
                        .addComponent(jCheckBox2)
                        .addGap(64, 64, 64)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listerestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listehotel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listelocationvacance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DataLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(listtransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(listdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        DataLayout.setVerticalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listelocationvacance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listtransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DataLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listerestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listehotel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        Menu.setBackground(new java.awt.Color(255, 225, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setText(" Flux RSS");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Newslettre   ");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setText("       Comptes");

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel7.setText("           DATA");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setText("     Publications");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/3D-User-Male-64.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/Gnome-Emblem-Photos-64.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/Email-boxy-48.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/RSS-48.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/3D-Database-64.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(23, 23, 23))
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/dao/graphique/agence-de-voyage2v2.jpg"))); // NOI18N

        javax.swing.GroupLayout fontLayout = new javax.swing.GroupLayout(font);
        font.setLayout(fontLayout);
        fontLayout.setHorizontalGroup(
            fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fontLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)))
        );
        fontLayout.setVerticalGroup(
            fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fontLayout.createSequentialGroup()
                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String donne = jComboBox1.getSelectedItem().toString();
        if (donne == "Transport" && jCheckBox1.isSelected()) {
            listtransport.setVisible(true);
            listdestination.setVisible(false);
            listdestination.setVisible(false);
            listehotel.setVisible(false);
            listerestaurant.setVisible(false);
            listelocationvacance.setVisible(false);
            font.setVisible(true);
        }

        if (donne == "Transport" && jCheckBox2.isSelected()) {
           AjouterTransport atransport = new AjouterTransport();
            atransport.setVisible(true);
            listdestination.setVisible(false);
            listehotel.setVisible(false);
            listerestaurant.setVisible(false);
            listelocationvacance.setVisible(false);
            
        }

        if (donne == "Destination" && jCheckBox1.isSelected()) {
            listtransport.setVisible(false);
            listdestination.setVisible(true);
            listehotel.setVisible(false);
            listerestaurant.setVisible(false);
            listelocationvacance.setVisible(false);
        }
        if (donne == "Destination" && jCheckBox2.isSelected()) {
            AjouterDestination adestination = new AjouterDestination();
            adestination.setVisible(true);
            this.setVisible(false);
        }
        if(donne=="Hotels" && jCheckBox1.isSelected() )

        {   listehotel.setVisible(true);
            listdestination.setVisible(false);
            listtransport.setVisible(false);
            listelocationvacance.setVisible(false);
            listerestaurant.setVisible(false);
        }
        if(donne=="Hotels" && jCheckBox2.isSelected() )

        {AjouterHotel ahotel=new AjouterHotel();
            ahotel.setVisible(true);

        }
        if(donne=="Restaurent" && jCheckBox2.isSelected() )

        {AjouterRestaurant ares =new AjouterRestaurant();
            ares.setVisible(true);

        }
        if(donne=="Location de vacance" && jCheckBox2.isSelected() )

        {AjouterLocation ares =new AjouterLocation();
            ares.setVisible(true);

        }
        if(donne=="Location de vacance" && jCheckBox1.isSelected() )

        {  listelocationvacance.setVisible(true);
            listehotel.setVisible(false);
            listdestination.setVisible(false);
            listtransport.setVisible(false);
            listerestaurant.setVisible(false);

        }
        if(donne=="Restaurent" && jCheckBox1.isSelected() )

        {   listerestaurant.setVisible(true);
            listehotel.setVisible(false);
            listdestination.setVisible(false);
            listtransport.setVisible(false);
            listelocationvacance.setVisible(false);

        }
    }//GEN-LAST:event_okActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        
          int ligneSelectionne = JTable3.getSelectedRow();
         
        Object l=JTable3.getValueAt(ligneSelectionne, 0);
         // 
        
         Hotel hotel=new Hotel();
        int id = (int)JTable3.getValueAt(ligneSelectionne, 0);
    
        ModifierHotel frame=new ModifierHotel(id);
        frame.setVisible(true);
        
      
      
           
           hotel.setIdhotel(id);
           frame.setT(hotel);
          
            frame.getjTextField3().setText((String)JTable3.getValueAt(ligneSelectionne,1));
             
        
            frame.getjTextField1().setText((String)JTable3.getValueAt(ligneSelectionne,3));
        
        
         frame.getjTextField2().setText((String)JTable3.getValueAt(ligneSelectionne,2));
        
         
         frame.getjTextArea1().setText((String)JTable3.getValueAt(ligneSelectionne,5));
       
         
          frame.getjComboBox1().setSelectedIndex((int)JTable3.getValueAt(ligneSelectionne,4)-1);
        
    }//GEN-LAST:event_modifierActionPerformed

    private void suphotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suphotActionPerformed
        // TODO add your handling code here:
        int ligneSelectionne = JTable3.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = JTable3.getValueAt(ligneSelectionne, 0);

        HotelDAO dd = new HotelDAO();
        dd.deleteHotel((int) l);
        JOptionPane.showMessageDialog(null, "suppr");
        JTable3.setModel(new AfficherHotel());

        jScrollPane1.setViewportView(JTable3);
    }//GEN-LAST:event_suphotActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int ligneSelectionne = tabledestination.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = tabledestination.getValueAt(ligneSelectionne, 0);

        DestinationDAO dao = new DestinationDAO();
        Destination destination = new Destination();
        destination.setIddestination(ligneSelectionne);

        destination.setPays((String) tabledestination.getValueAt(ligneSelectionne, 1));
        destination.setDescription((String)tabledestination.getValueAt(ligneSelectionne, 3));
        destination.setAdresse((String) tabledestination.getValueAt(ligneSelectionne, 2));
        destination.setIddestination((int) tabledestination.getValueAt(ligneSelectionne, 0));

        ModifierDestination frame = new ModifierDestination();

        frame.setD(destination);
        frame.getjTextField1().setText((String) tabledestination.getValueAt(ligneSelectionne, 1));
        frame.getjTextField2().setText((String) tabledestination.getValueAt(ligneSelectionne, 2));
        frame.getjTextField3().setText((String) tabledestination.getValueAt(ligneSelectionne, 3));
        frame.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void supdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supdesActionPerformed
        int ligneSelectionne = tabledestination.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = tabledestination.getValueAt(ligneSelectionne, 0);

        DestinationDAO dd = new DestinationDAO();
        dd.deleteDestination((int) l);
        JOptionPane.showMessageDialog(null, "supprimé");
        tabledestination.setModel(new AfficherDestinationFrameadmin());

        jScrollPane2.setViewportView(tabledestination);
    }//GEN-LAST:event_supdesActionPerformed

//    public JPanel getContenu() {
//        return Contenu;
//    }
//
//    public void setContenu(JPanel Contenu) {
//        this.Contenu = Contenu;
//    }

    public JPanel getData() {
        return Data;
    }

    public void setData(JPanel Data) {
        this.Data = Data;
    }

    public JPanel getMenu() {
        return Menu;
    }

    public void setMenu(JPanel Menu) {
        this.Menu = Menu;
    }

    public JPanel getListdestination() {
        return listdestination;
    }

    public void setListdestination(JPanel listdestination) {
        this.listdestination = listdestination;
    }

    public JPanel getListehotel() {
        return listehotel;
    }

    public void setListehotel(JPanel listehotel) {
        this.listehotel = listehotel;
    }

    public JPanel getListelocationvacance() {
        return listelocationvacance;
    }

    public void setListelocationvacance(JPanel listelocationvacance) {
        this.listelocationvacance = listelocationvacance;
    }

    public JPanel getListerestaurant() {
        return listerestaurant;
    }

    public void setListerestaurant(JPanel listerestaurant) {
        this.listerestaurant = listerestaurant;
    }

    public JPanel getListtransport() {
        return listtransport;
    }

    public void setListtransport(JPanel listtransport) {
        this.listtransport = listtransport;
    }

    private void modftraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modftraActionPerformed
        Transport t=new Transport();
        int ligneSelectionne = jTable1.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné
        ModifierTransport frame = new ModifierTransport();
        Object l = jTable1.getValueAt(ligneSelectionne, 0);
        String type = (String)jTable1.getValueAt(ligneSelectionne, 3);
        if (type == "Avion") {
            frame.getjComboBox1().setSelectedItem("Avion");
            t.setType(type);
        }
        if (type == "Transport") {
            frame.getjComboBox1().setSelectedItem("Transport");
            t.setType(type);
        }
        if (type == "Train") {
            frame.getjComboBox1().setSelectedItem("Train");
            t.setType(type);
        }
        if (type =="Bateau") {
        JComboBox c= new JComboBox();
        c.addItem("b");
        c.addItem("a");

frame.setjComboBox1(c);

//            frame.getjComboBox1().setSelectedIndex(3);
//            t.setType(type);
        }
        t.setIdtransport((int)l);
        frame.getjTextField1().setText((String)jTable1.getValueAt(ligneSelectionne, 1));
        t.setPays((String)jTable1.getValueAt(ligneSelectionne, 1));
        frame.getjTextField2().setText((String)jTable1.getValueAt(ligneSelectionne, 3));
        t.setType((String)jTable1.getValueAt(ligneSelectionne, 3));
        frame.getjTextArea1().setText((String)jTable1.getValueAt(ligneSelectionne, 4));
        t.setDescription((String)jTable1.getValueAt(ligneSelectionne, 4));
        frame.setT(t);
        frame.setVisible(true);
        System.out.println(l);

        }

        private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            int ligneSelectionne = JTable3.getSelectedRow();
            //on récupére la valeur de la première colonne de la ligne sélectionné

            Object l = JTable3.getValueAt(ligneSelectionne, 0);

            HotelDAO dd = new HotelDAO();
            dd.deleteHotel((int) l);
            JOptionPane.showMessageDialog(null, "suppr");
            JTable3.setModel(new AfficherTransportFrameadmin());

            jScrollPane1.setViewportView(JTable3);
        }

        private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            int ligneSelectionne = jTable5.getSelectedRow();
            //on récupére la valeur de la première colonne de la ligne sélectionné

            Object l = jTable5.getValueAt(ligneSelectionne, 0);

            RestaurantDAO dd = new RestaurantDAO();
            dd.deleteRestaurant((int) l);
            JOptionPane.showMessageDialog(null, "suppr");
            jTable5.setModel(new AfficherTransportFrameadmin());

            jScrollPane1.setViewportView(jTable5);
        }

        private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            int ligneSelectionne = jTable4.getSelectedRow();
            //on récupére la valeur de la première colonne de la ligne sélectionné

            Object l = jTable4.getValueAt(ligneSelectionne, 0);

            LocationDAO dd = new LocationDAO();
            dd.deleteLocation((int) l);
            JOptionPane.showMessageDialog(null, "suppr");
            jTable4.setModel(new AfficherTransportFrameadmin());

            jScrollPane1.setViewportView(jTable4);
    }//GEN-LAST:event_modftraActionPerformed

    private void suptranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suptranActionPerformed
        int ligneSelectionne = jTable1.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = jTable1.getValueAt(ligneSelectionne, 0);

        TransportDAO dd = new TransportDAO();
        dd.supprimerTransport((int) l);
        JOptionPane.showMessageDialog(null, "suppr");
        jTable1.setModel(new AfficherTransportFrameadmin());//refresh

        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_suptranActionPerformed

    private void restmodfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restmodfActionPerformed
          // TODO add your handling code here:
                  int ligneSelectionne = jTable5.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l=jTable5.getValueAt(ligneSelectionne, 0);
         
           
         Restaurent res =new Restaurent();
       int id=(int)jTable5.getValueAt(ligneSelectionne, 0);
          ModifierRestaurant frame=new ModifierRestaurant(id);
         frame.setVisible(true);
       
       res.setIdrestaurent(id);
         
          frame.setT(res);
        frame.getjTextField1().setText((String)jTable5.getValueAt(ligneSelectionne,3));
        frame.getjTextField2().setText((String)jTable5.getValueAt(ligneSelectionne,2));
          frame.getjTextField3().setText((String)jTable5.getValueAt(ligneSelectionne,1));
         frame.getjTextArea1().setText((String)jTable5.getValueAt(ligneSelectionne,5));
         frame.getjComboBox1().setSelectedIndex((int)jTable5.getValueAt(ligneSelectionne,4)-1);
        System.out.println(res);
        
        
    }//GEN-LAST:event_restmodfActionPerformed

    private void ressupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ressupActionPerformed
        // TODO add your handling code here:
        int ligneSelectionne = jTable5.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = jTable5.getValueAt(ligneSelectionne, 0);

        RestaurantDAO dd = new RestaurantDAO();
        dd.deleteRestaurant((int) l);
        JOptionPane.showMessageDialog(null, "suppression reussi");
        jTable5.setModel(new AfficheRestaurant());

        jScrollPane1.setViewportView(jTable5);
    }//GEN-LAST:event_ressupActionPerformed

    private void vacmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacmodifActionPerformed
       // TODO add your handling code here:
                 int ligneSelectionne = jTable4.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l=jTable4.getValueAt(ligneSelectionne, 0);
         
         
         LocationVacance loc =new LocationVacance();
       int id=(int)jTable4.getValueAt(ligneSelectionne, 0);
          Modifierlocation frame=new Modifierlocation(id);
         frame.setVisible(true);
       
        loc.setIdlocation(id);
         
          frame.setT(loc);
         
          
        frame.getjTextField1().setText((String)jTable4.getValueAt(ligneSelectionne,3));
        frame.getjTextField2().setText((String)jTable4.getValueAt(ligneSelectionne,2));
         frame.getjTextArea1().setText((String)jTable4.getValueAt(ligneSelectionne,4));
          
        frame.getjComboBox1().setSelectedItem(jTable4.getValueAt(ligneSelectionne,1));
        System.out.println(loc);
    }//GEN-LAST:event_vacmodifActionPerformed

    private void vacsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacsupActionPerformed
        // TODO add your handling code here:
        int ligneSelectionne = jTable4.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné

        Object l = jTable4.getValueAt(ligneSelectionne, 0);

        LocationDAO dd = new LocationDAO();
        dd.deleteLocation((int) l);
        JOptionPane.showMessageDialog(null, "suppression reussie");
        jTable4.setModel(new Affichelocation());

        jScrollPane1.setViewportView(jTable4);
    }//GEN-LAST:event_vacsupActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Data.setVisible(false);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Data.setVisible(false);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        new GestionUtilisateur().setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       Data.setVisible(false);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       Data.setVisible(false);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        new GUINewslettre().setVisible(true);
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Data.setVisible(false);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        new FluxRss().setVisible(true);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      Data.setVisible(true);
        listtransport.setVisible(false);
        listdestination.setVisible(false);
        listehotel.setVisible(false);
        listelocationvacance.setVisible(false);
        listerestaurant.setVisible(false);
        font.setVisible(true);
        
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data;
    private javax.swing.JTable JTable3;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel font;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel listdestination;
    private javax.swing.JPanel listehotel;
    private javax.swing.JPanel listelocationvacance;
    private javax.swing.JPanel listerestaurant;
    private javax.swing.JPanel listtransport;
    private javax.swing.JButton modftra;
    private javax.swing.JButton modifier;
    private javax.swing.JButton ok;
    private javax.swing.JButton ressup;
    private javax.swing.JButton restmodf;
    private javax.swing.JButton supdes;
    private javax.swing.JButton suphot;
    private javax.swing.JButton suptran;
    private javax.swing.JTable tabledestination;
    private javax.swing.JButton vacmodif;
    private javax.swing.JButton vacsup;
    // End of variables declaration//GEN-END:variables
}
