/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.dao.graphique;

import com.esprit.dao.graphique.table.AffRecommandationDestination;
import com.esprit.dao.entities.Fos_user;

/**
 *
 * @author Sony
 */
public class MesRecommandations extends javax.swing.JFrame {

    private Fos_user u;

    /**
     * Creates new form MesRecommandations
     */
    public MesRecommandations() {
        initComponents();
    }

    public Fos_user getU() {
        return u;
    }

    public void setU(Fos_user u) {
        this.u = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouprec = new javax.swing.ButtonGroup();
        RCD = new javax.swing.JPanel();
        Valider = new javax.swing.JButton();
        destination = new javax.swing.JRadioButton();
        hotel = new javax.swing.JRadioButton();
        Transport = new javax.swing.JRadioButton();
        restaurent = new javax.swing.JRadioButton();
        loctv = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recmd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RCD.setBackground(new java.awt.Color(250, 240, 240));

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        buttonGrouprec.add(destination);
        destination.setText("Destination");

        buttonGrouprec.add(hotel);
        hotel.setText("Hotels");

        buttonGrouprec.add(Transport);
        Transport.setText("Transport");

        buttonGrouprec.add(restaurent);
        restaurent.setText("Restaurent");

        buttonGrouprec.add(loctv);
        loctv.setText("Location Vacance");

        jScrollPane1.setViewportView(recmd);

        javax.swing.GroupLayout RCDLayout = new javax.swing.GroupLayout(RCD);
        RCD.setLayout(RCDLayout);
        RCDLayout.setHorizontalGroup(
            RCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RCDLayout.createSequentialGroup()
                .addGroup(RCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RCDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Valider)
                            .addGroup(RCDLayout.createSequentialGroup()
                                .addComponent(destination)
                                .addGap(26, 26, 26)
                                .addComponent(Transport, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(hotel)
                                .addGap(49, 49, 49)
                                .addComponent(restaurent)
                                .addGap(56, 56, 56)
                                .addComponent(loctv))))
                    .addGroup(RCDLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        RCDLayout.setVerticalGroup(
            RCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RCDLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(RCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination)
                    .addComponent(Transport)
                    .addComponent(hotel)
                    .addComponent(restaurent)
                    .addComponent(loctv))
                .addGap(18, 18, 18)
                .addComponent(Valider)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        System.out.println(u.getId());
        u.setId(1);
        if (destination.isSelected()) {
            recmd.setModel(new AffRecommandationDestination(u));

            jScrollPane1.setViewportView(recmd);
        }

    }//GEN-LAST:event_ValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesRecommandations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesRecommandations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesRecommandations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesRecommandations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesRecommandations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RCD;
    private javax.swing.JRadioButton Transport;
    private javax.swing.JButton Valider;
    private javax.swing.ButtonGroup buttonGrouprec;
    private javax.swing.JRadioButton destination;
    private javax.swing.JRadioButton hotel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton loctv;
    private javax.swing.JTable recmd;
    private javax.swing.JRadioButton restaurent;
    // End of variables declaration//GEN-END:variables
}
