/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.dao.graphique;

import com.esprit.dao.entities.Destination;
import com.esprit.dao.entities.Recommandation;
import com.esprit.dao.entities.Transport;
import com.esprit.dao.entities.Fos_user;
import com.esprit.*;
import com.esprit.dao.entities.Hotel;
import com.esprit.dao.entities.LocationVacance;
import com.esprit.dao.entities.Restaurent;
import com.esprit.implementations.DestinationDAO;
import com.esprit.implementations.HotelDAO;
import com.esprit.implementations.RecommandationDAO;
import com.esprit.implementations.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class Recommandationfr extends javax.swing.JFrame {

    Destination d;
    LocationVacance loc;
    Transport t;
    Restaurent rs;
    String tp;
    Hotel hot;
    Recommandation rc;
    Fos_user u;

    public Hotel getHot() {
        return hot;
    }

    public void setHot(Hotel hot) {
        this.hot = hot;
    }

    public Restaurent getRs() {
        return rs;
    }

    public void setRs(Restaurent rs) {
        this.rs = rs;
    }

    public LocationVacance getLoc() {
        return loc;
    }

    public void setLoc(LocationVacance loc) {
        this.loc = loc;
    }

    public Recommandation getRc() {
        return rc;
    }

    public void setRc(Recommandation rc) {
        this.rc = rc;
    }

    public Fos_user getU() {
        return u;
    }

    public void setU(Fos_user u) {
        this.u = u;
    }

    public String getTp() {
        return tp;
    }

    public void setTp(String tp) {
        this.tp = tp;
    }

    public Destination getD() {
        return d;
    }

    public void setD(Destination d) {
        this.d = d;
    }

    public Transport getT() {
        return t;
    }

    public void setT(Transport t) {
        this.t = t;
    }

    /**
     * Creates new form Recommandation
     */
    public Recommandationfr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        ev = new javax.swing.JComboBox();
        Evaluation = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 240, 240));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        Evaluation.setFont(new java.awt.Font("Adobe Arabic", 2, 18)); // NOI18N
        Evaluation.setText("Evaluation");

        jLabel5.setFont(new java.awt.Font("Adobe Arabic", 2, 18)); // NOI18N
        jLabel5.setText("Decription");

        jLabel11.setFont(new java.awt.Font("Adobe Arabic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Recommandation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Evaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ev, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(135, 135, 135))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Evaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String des = desc.getText();
        String note = (String) ev.getSelectedItem().toString();
   if( des.length()<1)
   {JOptionPane.showMessageDialog(null,"il faut remplir les champs");}
   else
        {
        int n = 0;
        if (note == "1") {
            n = 1;
        }
        if (note == "2") {
            n = 2;
        }
        if (note == "3") {
            n = 3;
        }
        if (note == "4") {
            n = 4;
        }
        if (note == "5") {
            n = 5;
        }
        if (tp == "destination") {
            System.out.println(tp);
            System.out.println(n);
            rc = new Recommandation(des, d.getPays(), d, u);
            RecommandationDAO rcm = new RecommandationDAO();
            rcm.ajouterRecommandationDestination(rc);
            DestinationDAO dao = new DestinationDAO();
            dao.evavluerDestination(n, d);
        }
        if (tp == "transport") {
            rc = new Recommandation(des, t.getPays(), t, u);
            RecommandationDAO rcm = new RecommandationDAO();
            rcm.ajouterRecommandationTransport(rc);
            TransportDAO dao = new TransportDAO();
            dao.evavluerTransport(n, t);
        }
        if (tp == "hotel") {
            rc = new Recommandation(des, hot.getPays(), hot, u);
            RecommandationDAO rcm = new RecommandationDAO();
            rcm.ajouterRecommandationHotel(rc);
            HotelDAO h=new HotelDAO();
            h.evaluerHotel(n, hot);
        }
        if (tp == "restaurent") {
            rc = new Recommandation(des, rs, u);
            RecommandationDAO rcm = new RecommandationDAO();
            rcm.ajouterRecommandationRestaurent(rc);
            RestaurantDAO r=new RestaurantDAO();
            r.evaluerRestaurant(n, rs);
        }
        if (tp == "location") {
            rc = new Recommandation(des, loc, u);
            RecommandationDAO rcm = new RecommandationDAO();
            rcm.ajouterRecommandationlocationVacance(rc);
            LocationDAO l=new LocationDAO();
            l.evaluerLocation(n, loc);
        }
         JOptionPane.showMessageDialog(null,"Recommandation réussie");}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recommandationfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recommandationfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recommandationfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recommandationfr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recommandationfr().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Evaluation;
    private javax.swing.JTextArea desc;
    private javax.swing.JComboBox ev;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
