fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
users_delete:
    path:     /delete/{id}
    defaults: { _controller: "PiGeneralBundle:Default:delete" }
users_activate:
    path:     /users_activate/{id}
    defaults: { _controller: "PiGeneralBundle:Default:users_activate" }
users_desactivate:
    path:     /users_desactivate/{id}
    defaults: { _controller: "PiGeneralBundle:Default:users_desactivate" }